pipeline {
  environment {
    nodejsimage = "cato-app-nodejs-v1"
    registry = "jshark2010"
    registryCredential = 'dockerhub'

  }
  agent any

  stages {

    stage('Export POAM') {
      steps{
        sh 'python3 poamExporter/exportPoam-0.1.5/exportPoam-0.1.5.py -c https://twistlock-console.oceast.cloudmegalodon.us -u jonathan@clearshark.com -p clearshark123! -o "ATO-PACKAGE:CATO-08252020" -id "" -t scans -m poamExporter/POAM_Export_Sample.xlsx -eu "Jonathan Spigler" -a ${JOB_BASE_NAME} -b $BUILD_NUMBER'
      }
    }
  }
  post {
        always {
            archiveArtifacts artifacts: '*.xlsx,*.csv', onlyIfSuccessful: true
        }
    }
}
